---
services:
  traefik:
    image: traefik:v3.2.0
    command: traefik --api.insecure=true --providers.docker=true --providers.docker.exposedByDefault=false
    ports:
      - 80:80
      - 8080:8080
    networks:
      default:
        aliases:
          - gitea.docker.test
          - drone.docker.test
          - maildev.docker.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gitea:
    image: gitea/gitea:1.22.3
    environment:
      GITEA__server__DISABLE_SSH: true
      GITEA__server__ROOT_URL: http://gitea.docker.test
      GITEA__webhook__ALLOWED_HOST_LIST: drone.docker.test
    labels:
      traefik.enable: true
      traefik.http.routers.gitea.entrypoints: http
      traefik.http.routers.gitea.rule: Host(`gitea.docker.test`)
      traefik.http.services.gitea.loadbalancer.server.port: 3000

  drone:
    image: drone/drone:2.24.0
    environment:
      DRONE_GITEA_CLIENT_ID: e775f224-b30a-4d3c-86c3-3311c8eb371e
      DRONE_GITEA_CLIENT_SECRET: gto_ugor3attlno7zuys24az4whvxewcutiau2dhejg63iyyv42ioy6a
      DRONE_GITEA_SERVER: http://gitea.docker.test
      DRONE_RPC_SECRET: d6be7f5ca3fa7ee2f5133f8f1cbcf00a
      DRONE_SERVER_HOST: drone.docker.test
      DRONE_SERVER_PROTO: http
      DRONE_WEBHOOK_ENDPOINT: http://host.docker.internal:3000
      DRONE_WEBHOOK_SECRET: f5281037ace0c2d7309afab60cfbaab3
    labels:
      traefik.enable: true
      traefik.http.routers.drone.entrypoints: http
      traefik.http.routers.drone.rule: Host(`drone.docker.test`)
      traefik.http.services.drone.loadbalancer.server.port: 80

  drone-runner-docker:
    image: drone/drone-runner-docker:1.8.3
    environment:
      DRONE_RPC_HOST: drone
      DRONE_RPC_PROTO: http
      DRONE_RPC_SECRET: d6be7f5ca3fa7ee2f5133f8f1cbcf00a
      DRONE_RUNNER_NETWORKS: drone-email-webhook_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  maildev:
    image: maildev/maildev:2.1.0
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080
      MAILDEV_INCOMING_USER: maildev
      MAILDEV_INCOMING_PASS: maildev
    labels:
      traefik.enable: true
      traefik.http.routers.maildev.entrypoints: http
      traefik.http.routers.maildev.rule: Host(`maildev.docker.test`)
      traefik.http.services.maildev.loadbalancer.server.port: 1080
    ports:
      - 1025:1025
